name: Basic CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install basic dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests streamlit praw sqlalchemy python-dotenv openai anthropic pandas openpyxl scikit-learn sentence-transformers matplotlib numpy
    
    - name: Check Python syntax
      run: |
        python -m py_compile config.py
        python -m py_compile database.py
        python -m py_compile reddit_scraper.py
        python -m py_compile llm_analyzer.py
        python -m py_compile data_organizer.py
        python -m py_compile main.py
        python -m py_compile streamlit_app.py
        python -m py_compile merged_analysis_page.py
        python -m py_compile advanced_analyzer.py
        python -m py_compile background_analyzer.py
        python -m py_compile clustering.py
        python -m py_compile insights_generator.py
        python -m py_compile structured_extractor.py
        python -m py_compile vectorizer.py
        python -m py_compile keyword_extractor.py
        python -m py_compile run_app.py
